export const ADMIN_USER_MANAGEMENT_ERROR_CODES = {
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_MANAGEMENT_FORBIDDEN: "USER_MANAGEMENT_FORBIDDEN",
  USER_SELF_ACTION_FORBIDDEN: "USER_SELF_ACTION_FORBIDDEN",
  USER_LAST_ADMIN_PROTECTED: "USER_LAST_ADMIN_PROTECTED",
  USER_ADMIN_UNIQUENESS_PROTECTED: "USER_ADMIN_UNIQUENESS_PROTECTED",
  USER_INVALID_STATE: "USER_INVALID_STATE",
  USER_ROLE_UNCHANGED: "USER_ROLE_UNCHANGED",
  USER_DUPLICATE_EMAIL: "USER_DUPLICATE_EMAIL",
  USER_REASON_REQUIRED: "USER_REASON_REQUIRED",
  USER_CREDENTIAL_CREATION_FAILED: "USER_CREDENTIAL_CREATION_FAILED",
  USER_CREDENTIAL_ACCOUNT_NOT_FOUND: "USER_CREDENTIAL_ACCOUNT_NOT_FOUND",
  USER_CURRENT_PASSWORD_INVALID: "USER_CURRENT_PASSWORD_INVALID",
  USER_PASSWORD_CHANGE_FAILED: "USER_PASSWORD_CHANGE_FAILED",
} as const;

export type AdminUserManagementErrorCode =
  (typeof ADMIN_USER_MANAGEMENT_ERROR_CODES)[keyof typeof ADMIN_USER_MANAGEMENT_ERROR_CODES];

export class AdminUserManagementError extends Error {
  constructor(
    readonly code: AdminUserManagementErrorCode,
    message: string,
  ) {
    super(message);
    this.name = "AdminUserManagementError";
  }
}
